### ISSUE TITLE
Main menu gui not displayed correctly

### ISSUE THREAD

**Issue by Werhas** [ThePinkPanzer/Godherja-Github-Version#251]
![2022_06_15_1](https://user-images.githubusercontent.com/83413510/173822812-109e83b7-99be-44c2-b8c9-90f899957459.png)

**Comment by ScionEol** [comment]
Fixed as of patch 0.2.6.03

**Comment by Tywele** [comment]
Not fixed sadly. I was having the same problem with the newest version.
[CK3 v1.6.1.2](https://cdn.discordapp.com/attachments/825739536042688592/993262133263466516/unknown.png)
[CK3 v1.6.1.1](https://cdn.discordapp.com/attachments/825739536042688592/993264756486062210/unknown.png)

I found I could workaround this issue by editing the settings.txt to have a smaller windowed resolution. This way when starting the game with the mod I could access the settings in the main menu and see that the problem is caused by the GUI scaling setting. In the images it was set to 100% and I could see everything properly by setting it to 130%. My monitors resolution is 1440p and I have no other mod installed.
